[package]
name = "buoyant"
version = "0.1.0"
authors = ["Riley Williams"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A library for building and rendering declarative SwiftUI-like UIs in Rust"
readme = "README.md"
repository = "https://github.com/riley-williams/buoyant"
keywords = ["ui", "graphics"]
exclude = [".github"]

[badges]
maintenance = { status = "experimental" }

[features]
default = []
std = []

[dependencies]
