[package]
name = "buoyant"
version = "0.1.7"
authors = ["Riley Williams"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A library for building and rendering declarative SwiftUI-like UIs in Rust"
readme = "README.md"
repository = "https://github.com/riley-williams/buoyant"
keywords = ["ui", "graphics"]
exclude = [".github"]

[badges]
maintenance = { status = "experimental" }

[features]
default = ["embedded-graphics"]
std = []
crossterm = ["dep:crossterm", "std"]
embedded-graphics = ["dep:embedded-graphics-core", "dep:embedded-graphics"]

[dependencies]
crossterm = { version = "^0.27", optional = true }
embedded-graphics-core = { version = "^0.4", optional = true }
embedded-graphics = { version = "^0.8", optional = true }
heapless = "^0.8"

[profile.release]
debug = true
