[package]
name = "buoyant"
version = "0.3.0-alpha.0"
authors = ["Riley Williams"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A library for building and rendering declarative SwiftUI-like UIs in Rust"
readme = "README.md"
repository = "https://github.com/riley-williams/buoyant"
keywords = ["ui", "graphics"]
exclude = [".github"]

[badges]
maintenance = { status = "experimental" }

[features]
default = ["crossterm"]
std = []
crossterm = ["dep:crossterm", "std"]

[dependencies]
crossterm = { version = "^0.28", optional = true }
embedded-graphics-core = { version = "^0.4" }
embedded-graphics = { version = "^0.8" }
heapless = "^0.8"
paste = "1.0.15"

[profile.release]
debug = true
