[package]
name = "buoyant"
version = "0.1.3"
authors = ["Riley Williams"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A library for building and rendering declarative SwiftUI-like UIs in Rust"
readme = "README.md"
repository = "https://github.com/riley-williams/buoyant"
keywords = ["ui", "graphics"]
exclude = [".github"]

[badges]
maintenance = { status = "experimental" }

[features]
default = ["std", "crossterm", "unicode"]
std = []
crossterm = ["dep:crossterm"]
unicode = ["dep:unicode-segmentation"]

[dependencies]
crossterm = { version = "0.27.0", optional = true }
unicode-segmentation = { version = "1.11.0", optional = true }

[profile.release]
debug = true
