[build]
rustflags = [
    "-Dclippy::nursery",
    "-Dclippy::pedantic",
    "-Dclippy::restriction",
    "-Aclippy::blanket_clippy_restriction_lints",
    ## Conflicts ##
    "-Aclippy::implicit_return",
    "-Aclippy::unseparated_literal_suffix",
    ## Bypasses ##
    "-Aclippy::cast_sign_loss",
    "-Aclippy::missing_panics_doc",
    "-Aclippy::cast_possible_truncation",
    "-Aclippy::cast_possible_wrap",
    "-Aclippy::single_call_fn",
    "-Aclippy::missing_docs_in_private_items",
    "-Aclippy::arbitrary_source_item_ordering",
    "-Aclippy::absolute_paths",
    "-Aclippy::missing_trait_methods",
    "-Aclippy::module_name_repetitions",
    "-Aclippy::arithmetic_side_effects",
    "-Aclippy::as_conversions",
    "-Aclippy::min_ident_chars",
    "-Aclippy::indexing_slicing",
    "-Aclippy::integer_division",
    "-Aclippy::integer_division_remainder_used",
    "-Aclippy::pattern_type_mismatch",
    "-Aclippy::exhaustive_enums",
    "-Aclippy::exhaustive_structs",
    "-Aclippy::shadow_unrelated",
    "-Aclippy::impl_trait_in_params",
    "-Aclippy::string_slice",
    "-Aclippy::float_arithmetic",
    "-Aclippy::cast_sign_loss",
    "-Aclippy::panic",
    "-Aclippy::unwrap_used",
    "-Aclippy::shadow_reuse",
    "-Aclippy::renamed_function_params",
    "-Aclippy::pub_use",
    "-Aclippy::question_mark_used",
    "-Aclippy::pub_with_shorthand",
    "-Aclippy::allow_attributes_without_reason",
    "-Aclippy::single_char_lifetime_names",
    "-Aclippy::ref_patterns",
    "-Aclippy::self_named_module_files",
    "-Aclippy::field_scoped_visibility_modifiers",
    "-Aclippy::print_stdout",
    "-Aclippy::use_debug",
    "-Aclippy::allow_attributes",
]
