name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install SDL2
        run: sudo apt-get update && sudo apt-get install libsdl2-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --all-features
  check-features:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check No Features
        run: cargo check --no-default-features
      - name: Check Crossterm
        run: cargo check --no-default-features --features "crossterm"
      - name: Check Embedded Graphics
        run: cargo check --no-default-features --features "embedded-graphics"
      - name: Check all features
        run: cargo check --all-features

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings

  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Markdown lint # v19.1.0
        uses: DavidAnson/markdownlint-cli2-action@05f32210e84442804257b2a6f20b273450ec8265
        with:
          globs: "**/*.md"

  test-book:
    name: test-book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir bin
          curl -sSL $url | tar -xz --directory=bin
          echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: Install SDL2
        run: sudo apt-get update && sudo apt-get install libsdl2-dev
      - name: Run book tests
        run: |
          # Create build deps for mdbook to reference
          cargo build --examples --all-features
          mdbook test -L target/debug/deps docs/book

  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check semver # v2.6
        uses: obi1kenobi/cargo-semver-checks-action@7272cc2caa468d3e009a2b0a9cc366839348237b

  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for typos # v1.30.2
        uses: crate-ci/typos@7bc041cbb7ca9167c9e0e4ccbb26f48eb0f9d4e0
